[buildPlans.iosevka-qp-lumi]
family = "Iosevka QP Lumi"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-qp-lumi.variants.design]
capital-a = "curly-serifless"
capital-c = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "asymmetric-serifless"
capital-q = "curly-tailed"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
c = "serifless"
f = "flat-hook-serifless"
g = "double-storey"
i = "hooky"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "flat-tailed"
m = "serifless"
r = "compact-serifless"
s = "serifless"
t = "flat-hook"
w = "straight-serifless"
z = "straight-serifless"
capital-delta = "curly"
capital-lambda = "curly-serifless"
lower-lambda = "curly-turn"
lower-chi = "straight-motion-serifed"
zero = "slashed-cutout"
one = "no-base"
four = "semi-open-non-crossing"
five = "upright-arched"
seven = "straight-serifed"
eight = "crossing-asymmetric"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold-tall"
dollar = "interrupted"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
cent = "bar-interrupted"
lig-ltgteq = "flat"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.iosevka-qp-lumi.variants.italic]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-k = "curly-serifless"
capital-l = "motion-serifed"
capital-n = "asymmetric-serifless"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "standing-open-bottom-right-serifed"
capital-s = "serifless"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive-with-horizontal-crossbar"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed-serifed"
j = "flat-hook-serifless"
k = "cursive-bottom-right-serifed"
l = "tailed"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-tailed-serifless"
t = "flat-hook-asymmetric"
v = "cursive-serifless"
w = "cursive-serifless"
x = "cursive"
y = "cursive-serifless"
z = "cursive"

  [buildPlans.iosevka-qp-lumi.ligations]
  inherits = "dlig"

[buildPlans.iosevka-qp-lumi.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-qp-lumi.weights.bold]
shape = 900
menu = 700
css = 700

[buildPlans.iosevka-qp-lumi.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-qp-lumi.widths.semiextended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.iosevka-qp-lumi.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-qp-lumi.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
