[buildPlans.iosevka-term-lumi]
family = "Iosevka Term Lumi"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-term-lumi.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-interrupted-serifless"
capital-c = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "open-serifless"
capital-q = "crossing"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
c = "serifless"
f = "flat-hook-serifless"
g = "double-storey-open"
i = "serifed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed"
m = "serifless"
r = "compact-serifless"
s = "serifless"
t = "flat-hook"
w = "straight-serifless"
z = "straight-serifless"
capital-delta = "straight"
lower-iota = "serifed-flat-tailed"
capital-lambda = "straight-serifless"
lower-lambda = "straight"
lower-chi = "straight-serifed"
cyrl-capital-ya = "straight-open-serifless"
cyrl-ya = "curly-open-serifless"
zero = "top-right-cutout"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "upright-arched"
seven = "straight-serifless-crossbar"
eight = "crossing-asymmetric"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
paren = "large-contour"
brace = "curly"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "et-toothed"
at = "compact"
dollar = "interrupted"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
cent = "bar-interrupted"
lig-ltgteq = "flat"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.iosevka-term-lumi.variants.italic]
capital-a = "curly-serifless"
capital-b = "standard-interrupted-serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "curly-serifless"
capital-l = "motion-serifed"
capital-m = "hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "standing-open-bottom-right-serifed"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive-with-horizontal-crossbar"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed"
g = "single-storey-flat-hook-earless-corner"
h = "tailed-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "cursive-bottom-right-serifed"
l = "serifed-flat-tailed"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-tailed-serifless"
r = "compact-serifless"
t = "flat-hook-asymmetric"
u = "tailed-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "cursive"
y = "cursive-flat-hook-serifless"
z = "cursive"
capital-delta = "curly"
capital-lambda = "curly-serifless"
lower-lambda = "tailed-turn"
lower-chi = "curly-serifed"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-el = "tailed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-er = "earless-corner-serifless"
cyrl-capital-u = "curly-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-capital-ya = "standing-open-serifless"
cyrl-ya = "standing-open-tailed-serifless"
zero = "oval-top-right-cutout"
two = "curly-neck"
three = "two-arcs"
five = "upright-flat"
six = "open-contour"
seven = "curly-serifless-crossbar"
nine = "open-contour"
ampersand = "et-tailed"
at = "compact"
percent = "rings-segmented-slash"
question = "smooth"

  [buildPlans.iosevka-term-lumi.ligations]
  inherits = "dlig"

[buildPlans.iosevka-term-lumi.weights.light]
shape = 200
menu = 300
css = 300

[buildPlans.iosevka-term-lumi.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-term-lumi.weights.medium]
shape = 600
menu = 500
css = 500

[buildPlans.iosevka-term-lumi.weights.bold]
shape = 900
menu = 700
css = 700

[buildPlans.iosevka-term-lumi.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-term-lumi.widths.semiextended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.iosevka-term-lumi.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-term-lumi.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
