[buildPlans.IosevkaTermKnit]
family = "Iosevka Term Knit"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaTermKnit.variants.design]
capital-a = "straight-tri-serifed"
capital-b = "standard-interrupted-bilateral-serifed"
capital-i = "serifed"
capital-k = "straight-serifed"
capital-n = "asymmetric-serifed"
capital-p = "open-serifed"
capital-q = "crossing"
capital-r = "straight-open-serifed"
a = "double-storey-serifless"
f = "flat-hook-serifed"
g = "double-storey-open"
i = "serifed"
j = "flat-hook-serifed"
k = "straight-serifed"
l = "serifed"
r = "compact-serifed"
t = "flat-hook"
capital-delta = "straight"
lower-iota = "serifed-flat-tailed"
capital-lambda = "straight-tri-serifed"
lower-lambda = "straight-turn"
lower-chi = "straight-serifed"
cyrl-capital-ya = "straight-open-serifed"
cyrl-ya = "curly-open-serifed"
zero = "top-right-cutout"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "upright-arched"
seven = "straight-serifed"
eight = "crossing-asymmetric"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "large-contour"
brace = "curly"
guillemet = "straight"
number-sign = "upright-open"
ampersand = "et-toothed"
at = "fourfold-tall"
dollar = "interrupted"
cent = "bar-interrupted"
bar = "natural-slope"
question = "corner"
lig-ltgteq = "flat"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.IosevkaTermKnit.variants.italic]
capital-a = "curly-tri-serifed"
capital-b = "standard-interrupted-bilateral-serifed"
capital-g = "toothless-corner-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-k = "curly-serifed"
capital-l = "serifed"
capital-m = "hanging-serifed"
capital-n = "asymmetric-serifed"
capital-p = "open-serifed"
capital-q = "open-swash"
capital-r = "standing-open-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-serifed"
capital-w = "curly-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "cursive-with-horizontal-crossbar"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifed"
f = "flat-hook-tailed"
g = "single-storey-flat-hook-serifed"
h = "tailed-serifed"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "cursive-serifed"
l = "serifed-flat-tailed"
m = "tailed-serifed"
n = "tailed-serifed"
p = "eared-serifed"
q = "tailed-motion-serifed"
r = "compact-serifed"
t = "flat-hook-asymmetric"
u = "tailed-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
x = "cursive"
y = "cursive-flat-hook-serifed"
z = "cursive"
capital-delta = "curly"
capital-lambda = "curly-tri-serifed"
lower-lambda = "curly-tailed-turn"
lower-chi = "curly-serifed"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-el = "tailed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-er = "earless-corner-serifed"
cyrl-capital-u = "curly-serifed"
cyrl-u = "cursive-flat-hook-serifed"
cyrl-capital-ya = "standing-open-serifed"
cyrl-ya = "standing-open-tailed-serifed"
zero = "oval-top-right-cutout"
two = "curly-neck"
three = "two-arcs"
five = "upright-flat"
six = "open-contour"
seven = "curly-serifed"
nine = "open-contour"
ampersand = "et-tailed"
at = "fourfold-solid-inner-tall"
percent = "rings-segmented-slash"
question = "smooth"

  [buildPlans.IosevkaTermKnit.ligations]
  inherits = "dlig"

[buildPlans.IosevkaTermKnit.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTermKnit.weights.Medium]
shape = 600
menu = 500
css = 500

[buildPlans.IosevkaTermKnit.weights.Bold]
shape = 900
menu = 700
css = 700

[buildPlans.IosevkaTermKnit.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaTermKnit.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaTermKnit.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaTermKnit.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTermKnit.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
